name: Test and deploy

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  test-context:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Dump GitHub context
        env:
          GITHUB_ACTIONS_CONTEXT: ${{ tojson(github) }}
        run: |
          python ./run.py
