name: Test and deploy

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  test-context:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Extract branch name
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Find last successful commit
        uses: nrwl/last-successful-commit-action@v1
        id: last_successful_commit
        with:
          branch: ${{ steps.extract_branch.outputs.branch }}
          workflow_id: test-context.yaml
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Dump GitHub context
        env:
          GITHUB_ACTIONS_CONTEXT: ${{ tojson(github) }}
        run: |
          python ./run.py
