name: Test and deploy

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  test-context:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Check status
        id: status
        run: |
          if python ./run.py; then
            echo "::set-output name=result::true"
          else
            echo "::set-output name=result::false"
          fi
      - if: steps.status.outputs.result == 'true'
        name: Check1
        run: echo "success"
      - if: steps.status.outputs.result == 'false'
        name: Check2
        run: echo "failed"
