name: Test and deploy

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  determine-type:
    runs-on: ubuntu-latest
    outputs:
      type: ${{ steps.if-staging.outputs.type || steps.if-prod.outputs.test || steps.if-pr.outputs.test }}
    steps:
      - id: if-staging
        if: ${{ github.ref == 'refs/heads/master' }}
        run: echo "::set-output name=type::STAGING"
      - id: if-prod
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: echo "::set-output name=type::PROD"
      - id: if-pr
        if: ${{ env.GITHUB_EVENT_NAME == 'pull_request' }}
        run: echo "::set-output name=test::PR"

  test-context:
    runs-on: ubuntu-latest
    steps:
      - name: echo type of build
        env:
          MESSAGE: ${{ needs.determine-type.outputs.type }} - START
        run: |
          echo "$GITHUB_ACTIONS_COMMITS"

